seed = 0
parent_dir = "exp/churn2/ddpm_mlp_best"
real_data_path = "data/churn2/"
model_type = "mlp"
num_numerical_features = 7
device = "cuda:1"

[model_params]
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    512,
    1024,
    1024,
    1024,
    1024,
    256,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 100
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 30000
lr = 0.00015044197980173247
weight_decay = 0.0
batch_size = 256

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 52000
batch_size = 10000
seed = 0

[eval.type]
eval_model = "mlp"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"
