seed = 0
parent_dir = "exp/house/ddpm_cb_best"
real_data_path = "data/house/"
model_type = "mlp"
num_numerical_features = 16
device = "cuda:0"

[model_params]
d_in = 17
num_classes = 0
is_y_cond = false

[model_params.rtdl_params]
d_layers = [
    128,
    512,
    512,
    512,
    512,
    256,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 30000
lr = 0.0013926185951764255
weight_decay = 0.0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 116000
batch_size = 30000
seed = 0

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"
model = "catboost"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
