seed = 1
parent_dir = "exp/churn2/ddpm_cb_best"
real_data_path = "data/churn2/"
model_type = "mlp"
num_numerical_features = 7
device = "cuda:1"

[model_params]
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    512,
    1024,
    1024,
    1024,
    1024,
    512,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 100
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 30000
lr = 0.0008057094292475385
weight_decay = 0.0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 26000
batch_size = 10000
seed = 0

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
